# Generated by Django 4.2.14 on 2024-09-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_benefactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charities.benefactor'),
        ),
    ]
