# Generated by Django 4.2.14 on 2024-09-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
