# Generated by Django 4.2.14 on 2024-11-15 17:34

from django.db import migrations, models

def extract_and_set_fields(apps, schema_editor):
    Person = apps.get_model('people', 'Person')
    
    for person in Person.objects.all():
        # استخراج نام و فامیل
        if person.fullname:
            fullname_parts = person.fullname.split(';')
            for part in fullname_parts:
                if 'first_name:' in part:
                    person.first_name = part.split(':')[1].strip()
                elif 'last_name:' in part:
                    person.last_name = part.split(':')[1].strip()
        
        # استخراج اطلاعات
        if person.information:
            info_parts = person.information.split(';')
            for part in info_parts:
                if 'id_code:' in part:
                    person.id_code = part.split(':')[1].strip()
                elif 'born_in:' in part:
                    person.born_in = part.split(':')[1].strip()
                elif 'birth_year:' in part:
                    person.birth_year = int(part.split(':')[1].strip())  # به یک عدد تبدیل کنید
        
        person.save()



class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='born_in',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='id_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RunPython(
            extract_and_set_fields,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='person',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='information',
        ),
    ]
